### PR TITLE
fixes #1

### LINKED ISSUE #1: Some endnotes are misnumbered
@davgross Tracking issue for misnumbered endnotes. 

Example: note 14 is in chapter 4, but note 15 is in chapter 3.

All notes should be examined to ensure they are in the correct order, otherwise reading systems get super screwed up (that's how I noticed).

### PR DESCRIPTION
**Pull request by davgross**
along with changes to chapter-3.xhtml and chapter-4.xhtml, fixes #1

### CODE REVIEW

**Comment by acabal** [comment]
Can you rebase these three pull requests into a single pull request/commit?  I could do it on my end but then I think I lose your contributor information

**Comment by davgross** [comment]
I did those edits in the github.com on-site editor because I got hung up somehow in creating my own repo (even after many months of climbing the treacherous learning curve, git is still kind of mysterious to me). I couldn't figure out a way of combining the three files into a single pull request/commit from the github.com web UI.

**Comment by acabal** [comment]
OK, I'll squash them on my end, but it'll probably lose your commiter information.

Github is a little tricky not just because Git has an absurdly crappy CLI but also because Github picked some less-than-helpful terminology like 'pull request'.  But you should be able to find various guides online on how to fork someone else's repo, make changes, and submit a pull request, so that next time we can keep your commiter data.

**Comment by acabal** [comment]
Combined #2, #3, and #4 and merged from command line.

**Pull request closed without merging**
