### PR TITLE
Correct translator surname

### PR DESCRIPTION
**Pull request by erinendrei**
The surname of the translator is Wiener, not Weiner, as in the standardebooks.org URL slug and Wikipedia link in content.opf: https://en.wikipedia.org/wiki/Leo_Wiener

The same spelling mistake occurs in Tolstoy's short fiction, but in that production the surname in the slug is wrong, so I don't know whether a PR like this one is enough or whether it's something you need to fix.

### CODE REVIEW

**Comment by acabal** [comment]
Does the colophon and also metadata in content.opf need to be fixed too?

I'm going to hold off on fixing Tolstoy for now because I think we're going to rename that slug to something shorter for works with a large amount of contributors. But if the error is also in the ebook itself you can open a PR for that.

**Comment by erinendrei** [comment]
No, the colophon and metadata were already correct. This PR changes all occurrences of the incorrect spelling. 

OK, sure. The error is also in the ebook for the short fiction, so I'll do that when I get a moment.

**Comment by acabal** [comment]
I'm looking at the colophon and his name is wrong in there at least. Can you correct that and also check the metadata?

**Comment by erinendrei** [comment]
I cannot see an occurrence of "Weiner" in the colophon of this book;
"Wiener" is correct. All my changes here are from "Weiner" to "Wiener".
(The colophon of Tolstoy's short fiction has the incorrect "Weiner".)

**Comment by acabal** [comment]
OK thanks1

**Pull request merged**
